# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_e82bjayc0i/clone/recipe, last modified Wed Jul 31 10:50:31 2024
# ------------------------------------------------

package:
  name: libxml2
  version: 2.13.1
source:
  patches: null
  sha256: d1d90c6cecedd4a572af7aef6606bc7a1b38bcc09deef182dd065685fbd8de3f
  url: https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.13.1/libxml2-v2.13.1.tar.gz
build:
  number: '2'
  run_exports:
    - libxml2 >=2.13.1,<2.14.0a0
  string: h0b34f26_2
requirements:
  build:
    - autoconf 2.71 pl5340h80987f9_0
    - automake 1.16.5 pl5340hca03da5_1
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - gdbm 1.18 h8fe7016_4
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libiconv 1.16 h80987f9_3
    - libllvm14 14.0.6 h7ec7a93_3
    - libtool 2.4.6 h313beb8_1009
    - llvm-tools 14.0.6 hfd8c8a6_3
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.4 h313beb8_0
    - perl 5.34.0 h1a28f6b_2
    - pkg-config 0.29.2 h1a28f6b_0
    - readline 8.2 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - icu 73.1 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libiconv 1.16 h80987f9_3
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - icu >=73.1,<74.0a0
    - libiconv >=1.16,<2.0a0
    - xz >=5.4.6,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - xmllint test.xml
  files:
    - test.xml
about:
  description: 'Though libxml2 is written in C a variety of language

    bindings make it available in other environments.

    '
  dev_url: https://gitlab.gnome.org/GNOME/libxml2/
  doc_url: https://gitlab.gnome.org/GNOME/libxml2/-/wikis/home
  home: https://gitlab.gnome.org/GNOME/libxml2/
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XML C parser and toolkit of Gnome
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e8d0d5fe-4e37-4dcf-ba52-7fc80533b996
  recipe-maintainers:
    - chenghlee
    - gillins
    - jakirkham
    - jschueller
    - mingwandroid
    - msarahan
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/libxml2-feedstock.git
  sha: 7ba1e01f5beceefc35b17cf32245e0e0902f5b47
