# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_51oymkxnaj/clone/recipe, last modified Thu Aug 29 09:09:13 2024
# ------------------------------------------------

package:
  name: cryptography
  version: 43.0.0
source:
  sha256: b88075ada2d51aa9f18283532c9f60e72170041bba88d7f37e49cbb10275299e
  url: https://pypi.io/packages/source/c/cryptography/cryptography-43.0.0.tar.gz
build:
  number: '0'
  script:
    - export OPENSSL_DIR=$PREFIX
    - /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_51oymkxnaj/croot/cryptography_1724940565328/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      -m pip install . -vv --no-deps --no-build-isolation
  string: py312hd4332d6_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h7ec7a93_3
    - llvm-tools 14.0.6 hfd8c8a6_3
    - rust 1.71.1 h80987f9_0
    - rust_osx-arm64 1.71.1 h313beb8_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.7.2 hca03da5_0
    - cffi 1.16.0 py312h80987f9_1
    - expat 2.6.2 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - maturin 1.5.1 py312hf0e4da2_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.14 h80987f9_0
    - pip 24.2 py312hca03da5_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.12.4 h99e199e_1
    - readline 8.2 h1a28f6b_0
    - setuptools 72.1.0 py312hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.43.0 py312hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - cffi >=1.12
    - openssl >=3.0.14,<4.0a0
    - python >=3.12,<3.13.0a0
  run_constrained:
    - bcrypt >=3.1.5
test:
  commands:
    - pip check
    - pytest -n auto -k "not (test_x509_csr_extensions or test_no_leak_free or test_no_leak_no_malloc
      or test_leak or test_create_certificate_with_extensions or test_ec_derive_private_key
      or test_ec_private_numbers_private_key or test_create_ocsp_request or test_write_pkcs12_key_and_certificates
      or test_errors or test_ec_private_numbers_private_key or test_create_crl_with_idp
      or test_no_leak_gc or test_x25519_pubkey_from_private_key)"
  requires:
    - certifi
    - cryptography-vectors 43.0.0.*
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-cov
    - pytest-xdist
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/
  home: https://github.com/pyca/cryptography
  license: Apache-2.0 OR BSD-3-Clause
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 51803b90-5696-4291-8b75-cac6f618c09f
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 4a9891308968f4004ec7b3e5f7ff7e64240b4944
