# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_ef9phnqphe/clone/recipe, last modified Tue Jun 11 15:37:52 2024
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 2.3.0
source:
  sha256: e26e42b5dc1280237491c025a7e6f23634126463abeace67655c725020d705fb
  url: https://github.com/conda/conda-package-handling/archive/2.3.0.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_ef9phnqphe/croot/conda-package-handling_1718138279942/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312hca03da5_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.3.11 hca03da5_0
    - expat 2.6.2 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.13 h1a28f6b_2
    - python 3.12.3 h99e199e_1
    - readline 8.2 h1a28f6b_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.3.11 hca03da5_0
    - expat 2.6.2 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.13 h1a28f6b_2
    - pip 24.0 py312hca03da5_0
    - python 3.12.3 h99e199e_1
    - readline 8.2 h1a28f6b_0
    - setuptools 69.5.1 py312hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.43.0 py312hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - conda-package-streaming >=0.9.0
    - python >=3.12,<3.13.0a0
    - zstandard >=0.15
test:
  commands:
    - pip check
    - pytest -v --cov=conda_package_handling --color=yes tests/
  imports:
    - conda_package_handling
    - conda_package_handling.api
  requires:
    - mock
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - requests
  source_files:
    - tests
about:
  description: '`conda` and `conda-build` use `conda_package_handling.api` to create
    and extract

    conda packages. This package also provides the `cph` command line tool to

    extract, create, and convert between formats.

    '
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://conda.github.io/conda-package-handling/
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Create and extract conda packages of various formats.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: efee76cc-9714-49b9-98b1-956c9645f50b
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
  remote_url: git@github.com:AnacondaRecipes/conda-package-handling-feedstock.git
  sha: d4199e8bbb72f41b10cc5a38bf544fa1eddd1049
