# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_63q0s9_5j8/clone/recipe, last modified Tue Apr 30 09:44:10 2024
# ------------------------------------------------

package:
  name: sqlite
  version: 3.45.3
source:
  patches: null
  sha256: b2809ca53124c19c60f42bf627736eae011afdcc205bb48270a5ee9a38191531
  url: https://www.sqlite.org/2024/sqlite-autoconf-3450300.tar.gz
build:
  number: '0'
  run_exports:
    - sqlite >=3.45.3,<4.0a0
  string: h80987f9_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h7ec7a93_3
    - libtool 2.4.6 h313beb8_1009
    - llvm-tools 14.0.6 hfd8c8a6_3
    - make 4.3 h620ffc9_1
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - ncurses 6.4 h313beb8_0
    - readline 8.1.2 h1a28f6b_1
    - zlib 1.2.13 h5a0b063_0
  run:
    - ncurses >=6.4,<7.0a0
    - readline >=8.1.2,<9.0a0
    - zlib >=1.2.13,<1.3.0a0
    - zlib >=1.2.13,<2.0a0
test:
  commands:
    - sqlite3 --version
    - test -f $PREFIX/bin/sqlite3
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
    - test -f $PREFIX/lib/pkgconfig/sqlite3.pc
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine. It is the most used database engine

    in the world.

    '
  dev_url: https://sqlite.org/src/dir?ci=trunk
  doc_url: https://www.sqlite.org/docs.html
  home: https://www.sqlite.org/
  license: blessing
  license_family: Other
  license_file: LICENSE.md
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 6321a6f2-c512-42f8-8da5-4a16f94f9792
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
    - xylar
  remote_url: git@github.com:AnacondaRecipes/sqlite-feedstock.git
  sha: c38575e40f2e78af6ead44f5f75b2d88d6a5b8d3
