# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_afk4ec3_e9/clone/recipe, last modified Tue Oct  1 10:00:45 2024
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2024.9.24
source:
  fn: cacert.pem
  sha256: 189d3cf6d103185fba06d76c1af915263c6d42225481a1759e853b33ac857540
  url: https://curl.se/ca/cacert-2024-09-24.pem
build:
  number: '0'
  string: hca03da5_0
requirements:
  build: []
  run: []
test:
  requires:
    - curl
about:
  description: Certificates for use with other packages.
  dev_url: https://github.com/curl/curl/blob/master/scripts/mk-ca-bundle.pl
  doc_url: https://github.com/curl/curl/blob/master/docs/SSLCERTS.md
  home: https://curl.se/docs/caextract.html
  license: MPL-2.0
  license_family: Other
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: af6ed51f-ce1b-4c0a-b97d-e32d844a7a3c
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/ca-certificates-feedstock.git
  sha: 5f225cead8d8a827f85f0a1faa5a05204ba4a5a8
