# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_40zr0_kae7/clone/recipe, last modified Fri Aug 30 08:07:43 2024
# ------------------------------------------------

package:
  name: python.app
  version: '3'
build:
  number: '1'
  string: py312h80987f9_1
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h7ec7a93_3
    - llvm-tools 14.0.6 hfd8c8a6_3
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.7.2 hca03da5_0
    - expat 2.6.2 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.14 h80987f9_0
    - python 3.12.4 h99e199e_1
    - readline 8.2 h1a28f6b_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.12,<3.13.0a0
test:
  files:
    - t.py
about:
  home: https://www.python.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Proxy on macOS letting Python libraries hook into the GUI event loop
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4025cdea-e529-46a0-ab14-bb14b8fc7ebc
  recipe-maintainers:
    - ChrisBarker-NOAA
    - cpbotha
    - hoechenberger
  remote_url: git@github.com:AnacondaRecipes/python.app-feedstock.git
  sha: 87283f59838171f8b58241b0750e8af133e1606c
