# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_5402h_fr1h/clone/recipe, last modified Fri Jun 16 10:56:49 2023
# ------------------------------------------------

package:
  name: krb5
  version: 1.20.1
source:
  sha256: ec3861c3bec29aa8da9281953c680edfdab1754d1b1db8761c1d824e4b25496a
  url: https://github.com/krb5/krb5/archive/krb5-1.20.1-final.tar.gz
build:
  ignore_run_exports:
    - libcxx
    - tk
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib
  number: '1'
  run_exports:
    - krb5 >=1.20.1,<1.21.0a0
  string: hf3e1bf2_1
requirements:
  build:
    - autoconf 2.71 pl5340h80987f9_0
    - bison 3.7.5 hc377ac9_1
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - clangxx_osx-arm64 14.0.6 h72866fe_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - flex 2.6.4 hc4ed4cf_1
    - gdbm 1.18 h8fe7016_4
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.2 h64d1936_2
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_0
    - libiconv 1.16 h1a28f6b_2
    - libllvm14 14.0.6 h7ec7a93_3
    - llvm-tools 14.0.6 hfd8c8a6_3
    - m4 1.4.18 h1230e6a_1
    - make 4.3 h620ffc9_1
    - ncurses 6.4 h313beb8_0
    - perl 5.34.0 h1a28f6b_2
    - pkg-config 0.29.2 h1a28f6b_0
    - readline 8.2 h1a28f6b_0
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h5a0b063_0
  host:
    - ca-certificates 2023.05.30 hca03da5_0
    - libedit 3.1.20221030 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.8 h1a28f6b_0
    - tk 8.6.12 hb8d0fd4_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - libedit >=3.1.20221030,<3.2.0a0
    - libedit >=3.1.20221030,<4.0a0
    - openssl >=3.0.8,<4.0a0
test:
  requires:
    - python 3.11.*
about:
  description: 'Kerberos is a network authentication protocol. It is designed to provide
    strong authentication for client/server applications by using secret-key cryptography.

    '
  dev_url: https://kerberos.org/dist/index.html
  doc_url: https://web.mit.edu/kerberos/krb5-1.20/doc/index.html
  home: https://web.mit.edu/kerberos/
  license: MIT
  license_family: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 54cba3a3-56d3-4fb7-85f2-119475e0db33
  recipe-maintainers:
    - chenghlee
    - mariusvniekerk
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/krb5-feedstock.git
  sha: ab05638e4d7f8fb8cec7f7e79a93b43b7461b5d1
