# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_ad321a45td/clone/recipe, last modified Tue Aug 13 11:46:41 2024
# ------------------------------------------------

package:
  name: menuinst
  version: 2.1.2
source:
  sha256: 6515a4e33cec8462cdb389c1c301ddbe0679c992c02e3ea42eea25225063b0e9
  url: https://github.com/conda/menuinst/archive/2.1.2.tar.gz
build:
  missing_dso_whitelist:
    - '**/libswift*'
  number: '0'
  script:
    - /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_ad321a45td/croot/menuinst_1723567614652/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
      -m pip install . -vv --no-build-isolation --no-deps
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.1.2
  string: py312hca03da5_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.7.2 hca03da5_0
    - expat 2.6.2 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.14 h80987f9_0
    - python 3.12.4 h99e199e_1
    - readline 8.2 h1a28f6b_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024a h04d1e81_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.7.2 hca03da5_0
    - expat 2.6.2 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.14 h80987f9_0
    - packaging 24.1 py312hca03da5_0
    - pip 24.2 py312hca03da5_0
    - python 3.12.4 h99e199e_1
    - readline 8.2 h1a28f6b_0
    - setuptools 72.1.0 py312hca03da5_0
    - setuptools-scm 8.1.0 py312hca03da5_0
    - setuptools_scm 8.1.0 hd3eb1b0_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.43.0 py312hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - SP_DIR="$(python -c 'import site; print(site.getsitepackages()[0])')"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_x86_64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_x86_64"
    - pytest tests/ -vvv --ignore=tests/test_schema.py --ignore=tests/test_elevation.py
  imports:
    - menuinst
    - menuinst.api
  requires:
    - conda
    - pip
    - pydantic
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: 'This package provides cross platform menu item installation for conda
    packages.


    If a conda package ships a menuinst JSON document under $PREFIX/Menu, conda will
    invoke

    menuinst to process the JSON file and install the menu items in your operating
    system.

    The menu items are removed when the package is uninstalled.

    '
  dev_url: https://github.com/conda/menuinst/
  doc_url: https://conda.github.io/menuinst/
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_family: BSD
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ad73deb2-a32d-483e-8369-06753df7546c
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  remote_url: git@github.com:AnacondaRecipes/menuinst-feedstock.git
  sha: acb55be7553b63dee2ed9d99b8ba144fa1ff4880
