# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_9fusbfzixa/clone/recipe, last modified Tue Apr 30 08:19:10 2024
# ------------------------------------------------

package:
  name: conda-content-trust
  version: 0.2.0
source:
  fn: conda-content-trust-0.2.0.tar.gz
  sha256: ded769f69a0491bd1e002ce949a332ae5a47a60ce733adb8a724802c8fdfe02b
  url: https://github.com/conda/conda-content-trust/archive/0.2.0.tar.gz
build:
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli
  number: '1'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_9fusbfzixa/croot/conda-content-trust_1714483157715/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py312hca03da5_1
requirements:
  host:
    - bzip2 1.0.8 h80987f9_5
    - ca-certificates 2024.3.11 hca03da5_0
    - editables 0.3 py312hca03da5_0
    - expat 2.6.2 h313beb8_0
    - hatch-vcs 0.3.0 py312hca03da5_1
    - hatchling 1.21.1 py312hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.13 h1a28f6b_0
    - packaging 23.2 py312hca03da5_0
    - pathspec 0.10.3 py312hca03da5_0
    - pip 23.3.1 py312hca03da5_0
    - pluggy 1.0.0 py312hca03da5_1
    - python 3.12.3 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - setuptools 68.2.2 py312hca03da5_0
    - setuptools-scm 8.0.4 py312hca03da5_0
    - sqlite 3.41.2 h80987f9_0
    - tk 8.6.12 hb8d0fd4_0
    - trove-classifiers 2023.10.18 py312hca03da5_0
    - typing-extensions 4.9.0 py312hca03da5_1
    - typing_extensions 4.9.0 py312hca03da5_1
    - tzdata 2024a h04d1e81_0
    - wheel 0.41.2 py312hca03da5_0
    - xz 5.4.6 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - cryptography >=41
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - conda-content-trust --help
  imports:
    - conda_content_trust
    - conda_content_trust.authentication
    - conda_content_trust.common
    - conda_content_trust.root_signing
    - conda_content_trust.signing
  requires:
    - pip
about:
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.md
  home: https://github.com/conda/conda-content-trust
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Signing and verification tools for conda
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 9f10a424-c3cb-406e-8815-e69685ba5839
  remote_url: git@github.com:AnacondaRecipes/conda-content-trust-feedstock.git
  sha: c005730d88c9a0765982c3dcdff73ffecbf7fafe
