# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /Users/builder/cbouss/perseverance-python-buildout/aggregate/pluggy-feedstock/recipe, last modified Sun Nov  5 19:44:15 2023
# ------------------------------------------------

package:
  name: pluggy
  version: 1.0.0
source:
  fn: pluggy-1.0.0.tar.gz
  sha256: 4224373bacce55f955a878bf9cfa763c1e360858e330072059e10bad68531159
  url: https://pypi.io/packages/source/p/pluggy/pluggy-1.0.0.tar.gz
build:
  number: '1'
  script: python -m pip install . --no-deps --ignore-installed
  string: py312hca03da5_1
requirements:
  host:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2023.08.22 hca03da5_0
    - expat 2.5.0 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.12 h1a28f6b_0
    - packaging 23.1 py312hca03da5_0
    - pip 23.3 py312hca03da5_0
    - python 3.12.0 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - setuptools 68.0.0 py312hca03da5_0
    - setuptools-scm 6.3.2 pyhd3eb1b0_0
    - setuptools_scm 6.3.2 hd3eb1b0_0
    - sqlite 3.41.2 h80987f9_0
    - tk 8.6.12 hb8d0fd4_0
    - tomli 1.2.2 pyhd3eb1b0_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.41.2 py312hca03da5_0
    - xz 5.4.2 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - python >=3.12,<3.13.0a0
test:
  command:
    - pip check
  imports:
    - pluggy
  requires:
    - pip
about:
  dev_url: https://github.com/pytest-dev/pluggy/
  doc_url: https://pluggy.readthedocs.io/en/latest/
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plugin registration and hook calling for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohnGreeley
    - nicoddemus
