# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_81ri4yfpjw/clone/recipe, last modified Thu Jul  4 09:04:20 2024
# ------------------------------------------------

package:
  name: packaging
  version: '24.1'
source:
  sha256: 026ed72c8ed3fcce5bf8950572258698927fd1dbda10a5e981cdf0ac37f4f002
  url: https://pypi.io/packages/source/p/packaging/packaging-24.1.tar.gz
build:
  number: '0'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_81ri4yfpjw/croot/packaging_1720101866878/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.3.11 hca03da5_0
    - expat 2.6.2 h313beb8_0
    - flit-core 3.9.0 py312hedbb292_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.14 h80987f9_0
    - pip 24.0 py312hca03da5_0
    - python 3.12.4 h99e199e_1
    - readline 8.2 h1a28f6b_0
    - setuptools 69.5.1 py312hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.43.0 py312hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest -v tests
  imports:
    - packaging
  requires:
    - pip
    - pretend
    - pytest >=6.2.0
  source_files:
    - tests
about:
  description: 'Reusable core utilities for various Python Packaging interoperability
    specifications.

    This library provides utilities that implement the interoperability specifications

    which have clearly one correct behaviour (eg: PEP 440) or benefit greatly from
    having

    a single shared implementation (eg: PEP 425).

    '
  dev_url: https://github.com/pypa/packaging
  doc_url: https://packaging.pypa.io
  home: https://github.com/pypa/packaging
  license: Apache-2.0 or BSD-2-Clause
  license_family: Apache
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 818ed930-7f54-4a30-ad5d-b8cc8d6d0500
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - nicoddemus
  remote_url: git@github.com:AnacondaRecipes/packaging-feedstock.git
  sha: 18c297c4ebb42012d36079fa674673cbef80fa15
  skip-lints:
    - missing_wheel
