# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a12xpo84t2/clone/recipe, last modified Mon Apr 29 08:54:06 2024
# ------------------------------------------------

package:
  name: idna
  version: '3.7'
source:
  sha256: 028ff3aadf0609c1fd278d8ea3089299412a7a8b9bd005dd08b9f8285bcb5cfc
  url: https://pypi.io/packages/source/i/idna/idna-3.7.tar.gz
build:
  number: '0'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a12xpo84t2/croot/idna_1714398852854/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py312hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_5
    - ca-certificates 2024.3.11 hca03da5_0
    - expat 2.6.2 h313beb8_0
    - flit-core 3.9.0 py312hedbb292_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.13 h1a28f6b_0
    - pip 23.3.1 py312hca03da5_0
    - python 3.12.3 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - setuptools 68.2.2 py312hca03da5_0
    - sqlite 3.41.2 h80987f9_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.41.2 py312hca03da5_0
    - xz 5.4.6 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
  imports:
    - idna
    - idna.codec
    - idna.compat
    - idna.core
  requires:
    - pip
about:
  description: 'A library to support the Internationalised Domain Names in Applications

    (IDNA) protocol as specified in RFC 5891. This version of the protocol

    is often referred to as "IDNA2008".

    '
  dev_url: https://github.com/kjd/idna
  doc_url: https://github.com/kjd/idna/blob/master/README.rst
  home: https://github.com/kjd/idna
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Internationalized Domain Names in Applications (IDNA).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a1364370-1196-4cdd-bc48-e075a469e616
  recipe-maintainers:
    - goanpeca
    - jschueller
  remote_url: git@github.com:AnacondaRecipes/idna-feedstock.git
  sha: 4eba6abb2b9cac8c230c3d9f094b26caec847125
