# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: libcurl
  version: 8.9.1
source:
  sha256: b57285d9e18bf12a5f2309fc45244f6cf9cb14734e7454121099dd0a83d669a3
  url: https://curl.se/download/curl-8.9.1.tar.bz2
build:
  number: 0
  run_exports:
    - libcurl >=8.9.1,<9.0a0
  string: h3e2b118_0
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h7ec7a93_3
    - llvm-tools 14.0.6 hfd8c8a6_3
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2024.7.2 hca03da5_0
    - krb5 1.20.1 hf3e1bf2_1
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.10.0 h02f6b3c_3
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.14 h80987f9_0
    - zlib 1.2.13 h18a0788_1
  run:
    - krb5 >=1.20.1,<1.21.0a0
    - libnghttp2 >=1.57.0
    - libnghttp2 >=1.57.0,<2.0a0
    - libssh2 >=1.10.0
    - libssh2 >=1.10.0,<2.0a0
    - openssl >=3.0.14,<4.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_url: https://curl.se/docs/
  home: https://curl.se/
  license: curl
  license_family: MIT
  license_url: https://curl.se/docs/copyright.html
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f3b78305-9243-49b3-8384-27a1f3edf723
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  remote_url: git@github.com:AnacondaRecipes/curl-feedstock.git
  sha: f40ddc96ec4014b80f30200ff4ccd503b434e1f1
