# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_f0q92r98ek/clone/recipe, last modified Thu Oct 17 14:38:04 2024
# ------------------------------------------------

package:
  name: conda
  version: 24.9.2
source:
  sha256: 0dcccbdaab96232dfee4471ca7ea7bbcacdcdf99d161cbb61bd7e92074fa7fcb
  url: https://github.com/conda/conda/releases/download/24.9.2/conda-24.9.2.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  script: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_f0q92r98ek/croot/conda_1729193891987/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation -vv && /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_f0q92r98ek/croot/conda_1729193891987/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m conda init --install
  string: py312hca03da5_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2024.9.24 hca03da5_0
    - curl 8.9.1 h02f6b3c_0
    - expat 2.6.3 h313beb8_0
    - gdbm 1.18 h8fe7016_4
    - gettext 0.21.0 hbdbcc25_2
    - git 2.45.2 pl5340hae58ea7_1
    - icu 73.1 h313beb8_0
    - krb5 1.20.1 hf3e1bf2_1
    - libcurl 8.9.1 h3e2b118_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libiconv 1.16 h80987f9_3
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.11.0 h3e2b118_0
    - libxml2 2.13.1 h0b34f26_2
    - llvm-openmp 14.0.6 hc6e5704_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - pcre2 10.42 hb066dcc_1
    - perl 5.34.0 h1a28f6b_2
    - readline 8.2 h1a28f6b_0
    - tk 8.6.14 h6ba3021_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  host:
    - boltons 23.0.0 py312hca03da5_0
    - brotli-python 1.0.9 py312h313beb8_8
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.9.24 hca03da5_0
    - certifi 2024.8.30 py312hca03da5_0
    - charset-normalizer 3.3.2 pyhd3eb1b0_0
    - expat 2.6.3 h313beb8_0
    - hatch-vcs 0.3.0 py312hca03da5_1
    - hatchling 1.25.0 py312hca03da5_0
    - idna 3.7 py312hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - menuinst 2.1.2 py312hca03da5_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - packaging 24.1 py312hca03da5_0
    - pathspec 0.10.3 py312hca03da5_0
    - pip 24.2 py312hca03da5_0
    - platformdirs 3.10.0 py312hca03da5_0
    - pluggy 1.0.0 py312hca03da5_1
    - pysocks 1.7.1 py312hca03da5_0
    - python 3.12.7 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - requests 2.32.3 py312hca03da5_0
    - ruamel.yaml 0.18.6 py312h80987f9_0
    - ruamel.yaml.clib 0.2.8 py312h80987f9_0
    - setuptools 75.1.0 py312hca03da5_0
    - setuptools-scm 8.1.0 py312hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tqdm 4.66.5 py312h989b03a_0
    - trove-classifiers 2023.10.18 py312hca03da5_0
    - tzdata 2024b h04d1e81_0
    - urllib3 2.2.3 py312hca03da5_0
    - wheel 0.44.0 py312hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=23.11.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.12,<3.13.0a0
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
    - zstandard >=0.19.0
  run_constrained:
    - conda-build >=3.27
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  downstreams:
    - conda-smithy
  imports:
    - conda
    - conda_env
  requires: null
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://docs.conda.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f0de3cd1-90bf-4074-8fe4-eb6713b94c80
  remote_url: git@github.com:AnacondaRecipes/conda-feedstock.git
  sha: fe143ae7f7f27e618dae027883730c83439702ef
  skip-lints:
    - missing_pip_check
    - python_build_tool_in_run
