# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_84tggexg5i/clone/recipe, last modified Tue Aug 20 11:51:39 2024
# ------------------------------------------------

package:
  name: libarchive
  version: 3.7.4
source:
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
    - patches/0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
    - patches/0006-VC-openssl-define-inline-as-__inline.patch
    - patches/0007-CMake-VC9-compatibility-ignore-some-warnings.patch
    - patches/0008-VC9-compatibility-remove-C99.patch
    - patches/0009-CMake-Force-Multi-threaded-DLL-runtime.patch
  sha256: 7875d49596286055b52439ed42f044bd8ad426aa4cc5aabd96bfe7abb971d5e8
  url: https://github.com/libarchive/libarchive/releases/download/v3.7.4/libarchive-3.7.4.tar.gz
build:
  ignore_run_exports:
    - openssl
  number: '0'
  run_exports:
    - libarchive >=3.7.4,<3.8.0a0
  string: h8f13d7a_0
requirements:
  build:
    - bzip2 1.0.8 h80987f9_6
    - c-ares 1.19.1 h80987f9_0
    - ca-certificates 2024.7.2 hca03da5_0
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_1
    - clang-14 14.0.6 default_h1b80db6_1
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_1
    - cmake 3.26.4 h5d7ac33_0
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - expat 2.6.2 h313beb8_0
    - krb5 1.20.1 hf3e1bf2_1
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_1
    - libcurl 8.7.1 h3e2b118_0
    - libcxx 14.0.6 h848a8c0_0
    - libedit 3.1.20230828 h80987f9_0
    - libev 4.33 h1a28f6b_1
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h7ec7a93_3
    - libnghttp2 1.57.0 h62f6fdd_0
    - libssh2 1.11.0 h3e2b118_0
    - libuv 1.48.0 h80987f9_0
    - llvm-tools 14.0.6 hfd8c8a6_3
    - lz4-c 1.9.4 h313beb8_1
    - ncurses 6.4 h313beb8_0
    - ninja-base 1.10.2 h525c30c_5
    - openssl 3.0.14 h80987f9_0
    - patch 2.7.6 h1a28f6b_1001
    - rhash 1.4.3 h02f6b3c_0
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
    - zstd 1.5.5 hd90d995_2
  host:
    - bzip2 1.0.8 h80987f9_6
    - icu 73.1 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libiconv 1.16 h80987f9_3
    - libxml2 2.13.1 h0b34f26_2
    - lz4-c 1.9.4 h313beb8_1
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
    - zstd 1.5.2 h8574219_0
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libiconv >=1.16,<2.0a0
    - libxml2 >=2.13.1,<2.14.0a0
    - lz4-c >=1.9.4,<1.10.0a0
    - xz >=5.4.6,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
    - zstd >=1.5.2,<1.6.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
    - test -f "${PREFIX}/include/archive.h"
    - test -f "${PREFIX}/include/archive_entry.h"
    - test -f "${PREFIX}/lib/libarchive.a"
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - pushd test-archives
    - bsdtar -vxf hello_world.xar 2>&1 | rg "x hello_world"
    - bsdtar -vxf archive.7z 2>&1 | rg "x 7zip-archive"
    - bsdtar -vxf hello_world.tar.zst 2>&1 | rg "greets"
    - popd
  files:
    - test-archives/archive.7z
    - test-archives/hello_world.tar.zst
    - test-archives/hello_world.xar
  requires:
    - ripgrep
about:
  description: 'Libarchive is an open-source BSD-licensed C programming library that
    provides streaming access

    to a variety of different archive formats, including tar, cpio, pax, Zip, and
    ISO9660 images.

    The distribution also includes bsdtar and bsdcpio, full-featured implementations
    of tar and cpio

    that use libarchive.

    When reading archives, libarchive uses a robust automatic format detector that
    can automatically handle archives

    that have been compressed with gzip, bzip2, xz, lzip, and several other popular
    compression algorithms.

    '
  dev_url: https://github.com/libarchive/libarchive
  doc_url: https://github.com/libarchive/libarchive/wiki
  home: https://libarchive.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Multi-format archive and compression library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8482927b-ab40-4fe6-8670-9f0b91bd3ba9
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/libarchive-feedstock.git
  sha: 5de12bc96cbcd340f637e34f108bfb90832157ef
  skip-lints:
    - host_section_needs_exact_pinnings
    - missing_tests
